# Generated by Django 4.2.22 on 2025-06-10 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_remove_empleado_nombre_empleado_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='dias_a_tomar',
            field=models.PositiveIntegerField(default=3, verbose_name='Días a tomar'),
            preserve_default=False,
        ),
    ]
