# Generated by Django 5.2.1 on 2025-05-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('puesto', models.CharField(max_length=50)),
                ('sucursal', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
