# Generated by Django 5.2.1 on 2025-06-05 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(default='S/D', max_length=20, verbose_name='Apellido Materno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(default='S/D', max_length=20, verbose_name='Apellido Paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='clabe_interbancaria',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horas_extras',
            field=models.CharField(choices=[('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default='0', max_length=10, verbose_name='Horas Extras'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(default='S/D', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sueldo_quincenal',
            field=models.CharField(choices=[('4200.00', '$4,200.00'), ('4500.00', '$4,500.00'), ('5000.00', '$5,000.00'), ('5500.00', '$5,500.00'), ('6000.00', '$6,000.00'), ('6500.00', '$6,500.00')], default='4200.00', max_length=10, verbose_name='Sueldo Quincenal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('auxiliar_general', 'Auxiliar General'), ('chofer', 'Chofer'), ('chofer_camion', 'Chofer de Camion'), ('encargado_de_area', 'Encargado de Area'), ('almacen', 'Almacén'), ('seguridad', 'Seguridad'), ('cocinera', 'Cocinero(a)')], default='ventas', max_length=30, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sucursal',
            field=models.CharField(choices=[('admin', 'Admin'), ('bonfil', 'Bonfil'), ('cabos', 'Cabos'), ('cedis', 'Cedis'), ('costa', 'Costa'), ('puerto', 'Puerto')], default='centro', max_length=20, verbose_name='Sucursal'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_empleados/')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuarios.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_retorno', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
            ],
        ),
    ]
