# Generated by Django 4.2.22 on 2025-06-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_vacacion_aprobado_por_vacacion_dias_a_tomar'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='es_administrador',
            field=models.BooleanField(default=False, verbose_name='¿Es administrador?'),
        ),
    ]
