# Generated by Django 5.2.3 on 2025-07-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_empleado_es_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('auxiliar_general', 'Auxiliar General'), ('chofer', 'Chofer'), ('chofer_camion', 'Chofer de Camion'), ('encargado_de_area', 'Encargado de Area'), ('almacen', 'Almacén'), ('seguridad', 'Seguridad'), ('cocinera', 'Cocinero(a)'), ('supervisor_montajes', 'Supervisor de Montaje')], default='ventas', max_length=30, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo_quincenal',
            field=models.CharField(choices=[('4200.00', '$4,200.00'), ('4500.00', '$4,500.00'), ('5000.00', '$5,000.00'), ('5500.00', '$5,500.00'), ('6000.00', '$6,000.00'), ('6500.00', '$6,500.00'), ('7000.00', '$7,500.00'), ('8000.00', '$8,500.00'), ('9000.00', '$9,500.00')], default='4200.00', max_length=10, verbose_name='Sueldo Quincenal'),
        ),
    ]
