# Generated by Django 5.2.3 on 2025-07-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_feriado_alter_empleado_puesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('evento', models.CharField(max_length=200)),
                ('encargado_evento', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('foto_ine', models.ImageField(upload_to='eventuales/ine/')),
                ('foto_licencia', models.ImageField(upload_to='eventuales/licencia/')),
            ],
        ),
    ]
