# Generated by Django 5.2.3 on 2025-07-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_eventual'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_identificacion_frente',
            field=models.ImageField(blank=True, null=True, upload_to='empleados_identificaciones/', verbose_name='Foto Identificación Frente'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto_identificacion_reverso',
            field=models.ImageField(blank=True, null=True, upload_to='empleados_identificaciones/', verbose_name='Foto Identificación Reverso'),
        ),
    ]
