# Generated by Django 5.2.3 on 2025-07-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_empleado_foto_identificacion_frente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto_identificacion_reverso',
            field=models.ImageField(upload_to='empleados_identificaciones/', verbose_name='Foto Identificación Reverso'),
        ),
    ]
