# Generated by Django 5.2.3 on 2025-07-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_empleado_foto_identificacion_reverso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto_identificacion_frente',
            field=models.ImageField(upload_to='empleados_identificaciones/', verbose_name='Foto Identificación Frente'),
        ),
    ]
