# Generated by Django 4.2.22 on 2025-07-31 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_empleado_foto_identificacion_frente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('encargado', 'Encargado'), ('vendedor', 'Vendedor'), ('auxiliar_general', 'Auxiliar General'), ('chofer', 'Chofer'), ('chofer_camion', 'Chofer de Camion'), ('encargado_de_area', 'Encargado de Area'), ('encargado_de_almacen', 'Almacén'), ('seguridad', 'Seguridad'), ('cocinera', 'Cocinero(a)'), ('supervisor_montajes', 'Supervisor de Montaje')], default='ventas', max_length=30, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sucursal',
            field=models.CharField(choices=[('chichen', 'Chichen'), ('bonfil', 'Bonfil'), ('cabos', 'Cabos'), ('cedis', 'Cedis'), ('costa', 'Costa'), ('puerto', 'Puerto'), ('ventas', 'Ventas')], default='centro', max_length=20, verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo_quincenal',
            field=models.CharField(choices=[('4200.00', '$4,200.00'), ('4500.00', '$4,500.00'), ('5000.00', '$5,000.00'), ('5500.00', '$5,500.00'), ('6000.00', '$6,000.00'), ('6500.00', '$6,500.00'), ('7000.00', '$7,500.00'), ('8000.00', '$8,500.00'), ('9000.00', '$9,500.00'), ('10000.00', '$10,000.00'), ('11000.00', '$11,000.00'), ('12500.00', '$12,500.00'), ('15000.00', '$15,000.00'), ('20000.00', '$20,000.00'), ('30000.00', '$30,000.00')], default='4200.00', max_length=10, verbose_name='Sueldo Quincenal'),
        ),
        migrations.CreateModel(
            name='PrimaVacacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año cumplido')),
                ('fecha_generada', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
            ],
            options={
                'unique_together': {('empleado', 'anio')},
            },
        ),
    ]
