# Generated by Django 4.2.22 on 2025-08-05 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_empleado_puesto_alter_empleado_sucursal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finiquito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateField()),
                ('salario_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_aguinaldo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_aguinaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_vacaciones', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_vacaciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_prima_vacacional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('concepto_adicional', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('concepto_descuento', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('firmado', 'Firmado')], default='pendiente', max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='finiquitos/')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finiquitos', to='usuarios.empleado')),
            ],
        ),
    ]
