# Generated by Django 4.2.22 on 2025-08-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_finiquito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finiquito',
            name='archivo_pdf',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='concepto_adicional',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='dias_aguinaldo',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='dias_vacaciones',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='fecha_generacion',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='monto_adicional',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='monto_aguinaldo',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='monto_descuento',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='monto_horas_extra',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='monto_prima_vacacional',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='monto_vacaciones',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='salario_diario',
        ),
        migrations.RemoveField(
            model_name='finiquito',
            name='total_neto',
        ),
        migrations.AddField(
            model_name='finiquito',
            name='concepto_extra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finiquito',
            name='importe_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='finiquito',
            name='importe_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finiquito',
            name='concepto_descuento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finiquito',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado'),
        ),
        migrations.AlterField(
            model_name='finiquito',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='finiquito',
            name='horas_extra',
            field=models.IntegerField(default=0),
        ),
    ]
